config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get  "/help", to: "static_pages#help"
    get  "/about", to: "static_pages#about"
    get  "/contact", to: "static_pages#contact"
    get  "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get  "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save :email_downcase
  validates :name, presence: true, length: {maximum: Settings.max_length_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            length: {maximum: Settings.max_length_email},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, presence: true,
            length: {minimum: Settings.min_length_pass}

  has_secure_password

  private
  def email_downcase
    email.downcase!
  end

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :set_locale

  private

  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale = if I18n.available_locales.include?(locale)
                    locale
                  else I18n.default_locale
                  end
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = t "danger"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      flash[:success] = t "welcome_app"
      redirect_to @user
    else
      flash[:danger] = t "error_signup"
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    return redirect_to root_path if @user
    flash[:danger] = t "error_find_user"
    redirect_to signup_path
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t ".ror_ttr_sa"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("Rails"), "http://www.railstutorial.org/" %>
    <%= t "by" %>
    <%= link_to "Michael Hartl", "http://www.michaelhartl.com/" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("about"), about_path %></li>
      <li><%= link_to t("contact"), contact_path %></li>
      <li><%= link_to t("new"), "http://news.railstutorial.org/" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("sample_app"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("users"), '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("profile"), current_user %></li>
              <li><%= link_to t("settings"), '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path %></li>
        <% end %>
        <li><%= link_to t("english"), locale: "en" %></li>
        <li><%= link_to t("vietnam"), locale: "vi" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "ror_ttr_sa" %></title>
    <%= render "layouts/shim" %>
    <%= render "layouts/rails_default" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug params if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_contains" %> <%= pluralize @user.errors.count, "error" %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t(".about") %>
<h1><%= t ".about" %></h1>
<p>
  <%= t ".content_html",
    link1: link_to("<em>Ruby on Rails Tutorial</em>".html_safe, "http://www.railstutorial.org/"),
    link2: link_to(t(".book"), "http://www.railstutorial.org/book"),
    link3: link_to(t(".screencast_series"), "http://screencasts.railstutorial.org/"),
    link4: link_to("Ruby on Rails", "http://rubyo nrails.org/") %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".contact") %>
<h1><%= t ".contact" %></h1>
<p>
  <%= t ".content_html",
  link1: link_to(t(".contact_page"), "http://www.railstutorial.org/contact") %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".help") %>
<h1><%= t ".help" %></h1>
<p>
  <%= t ".content_html",
    link1: link_to(t(".Rails_ttr_hp_st"), "http://www.railstutorial.org/help"),
    link2: link_to(t(".Ror_ttr"), "http://www.railstutorial.org/book") %>
</p>

app/views/static_pages/home.html.erb
<% provide :title, t(".home") %>
<div class="center jumbotron">
  <h1><%= t ".welcome_sample" %></h1>

  <h2>
    <%= t ".content_html",
    link1: link_to("Ruby on Rails Tutorial", "http://www.railstutorial.org/") %>
  </h2>

    <%= link_to t(".sign_up"), signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".title" %></h1>
<p><%= t ".info_signup" %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @user, url: signup_path do |f| %>
      <%= render "shared/error_messages" %>

      <%= f.label :name, t("name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, t("email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, t("pass") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t("confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit t("create"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>